# Generated by Django 5.2.8 on 2025-12-01 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["id"],
                "permissions": [
                    ("change_user_activity", "Can change user activity"),
                    ("view_users_list", "Can view users list"),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
