# Generated by Django 5.2.8 on 2025-11-28 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(max_length=120, verbose_name="Тема письма")),
                ("body", models.TextField(verbose_name="Тело письма")),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.CharField(max_length=254, unique=True, verbose_name="Адрес электронной почты")),
                ("full_name", models.CharField(blank=True, max_length=150, null=True, verbose_name="Ф.И.О.")),
                ("comment", models.TextField(blank=True, null=True, verbose_name="Комментарий")),
            ],
            options={
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mailing_start_datetime", models.DateTimeField(verbose_name="Дата и время первой отправки")),
                ("mailing_end_datetime", models.DateTimeField(verbose_name="Дата и время окончания отправки")),
                (
                    "status",
                    models.CharField(
                        choices=[("created", "Создана"), ("launched", "Запущена"), ("completed", "Завершена")],
                        default="created",
                        verbose_name="Статус",
                    ),
                ),
                ("message", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="mailing.message")),
                ("recipients", models.ManyToManyField(related_name="recipients", to="mailing.recipient")),
            ],
        ),
    ]
