# Generated by Django 5.2.8 on 2025-11-28 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={"ordering": ["-id"], "verbose_name": "Рассылка", "verbose_name_plural": "Рассылки"},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-id"], "verbose_name": "Сообщение", "verbose_name_plural": "Сообщения"},
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={"ordering": ["-id"], "verbose_name": "Получатель", "verbose_name_plural": "Получатели"},
        ),
    ]
