# Generated by Django 5.2.8 on 2025-11-29 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_alter_mailing_options_alter_message_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="status",
        ),
    ]
