# Generated by Django 5.2.8 on 2025-11-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_remove_mailing_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[("created", "Создана"), ("launched", "Запущена"), ("completed", "Завершена")],
                default="created",
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="mailing_end_datetime",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата и время окончания отправки"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="mailing_start_datetime",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата и время первой отправки"),
        ),
    ]
