# Generated by Django 5.2.8 on 2025-11-29 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_alter_mailing_message_alter_mailing_recipients_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingattempt",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mailing.recipient",
                verbose_name="Получатель",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(
                help_text="Для выделения нескольких получателей используйте комбинации ЛКМ+Ctrl или ЛКМ+Shift.",
                related_name="recipients",
                to="mailing.recipient",
                verbose_name="Получатели рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="mailing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mailing.mailing", verbose_name="Рассылка"
            ),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="server_response",
            field=models.TextField(blank=True, null=True, verbose_name="Ответ почтового сервера"),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("successfully", "успешно"), ("unsuccessfully", "не успешно")],
                null=True,
                verbose_name="Статус",
            ),
        ),
    ]
