# Generated by Django 5.2.8 on 2025-11-30 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0006_mailingattempt_recipient_alter_mailing_recipients_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mailing",
            old_name="mailing_end_datetime",
            new_name="end_datetime",
        ),
        migrations.RenameField(
            model_name="mailing",
            old_name="mailing_start_datetime",
            new_name="start_datetime",
        ),
    ]
