# Generated by Django 5.2.8 on 2025-11-30 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0008_mailing_owner_message_owner_recipient_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["-id"],
                "permissions": [("disable_activity", "Can disable activity")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
