# Generated by Django 5.2.8 on 2025-11-30 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0009_alter_mailing_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["-id"],
                "permissions": [("change_mailing_activity", "Can change mailing activity")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
