# Generated by Django 5.2.8 on 2025-12-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0010_alter_mailing_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingattempt",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Допуск рассылки"),
        ),
    ]
