# Generated by Django 5.2.8 on 2025-12-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0011_mailingattempt_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailingattempt",
            name="is_active",
        ),
        migrations.AddField(
            model_name="mailing",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Допуск рассылки"),
        ),
    ]
